import os, time

configuratinatorstring="# generated by configuratinator"

while True:
    try:
        with open("/etc/resolv.conf", "r") as f:
            if not f.readline().startswith(configuratinatorstring):
                os.system("rm /etc/resolv.conf")
                os.system("cp /etc/resolv.configuratinator /etc/resolv.conf")
                print("config change detected and resolved!")
        time.sleep(10)
    except Exception:
        print("no resolvconf found")
        try:
            os.system("touch /etc/resolv.conf")
        except Exception:
            pass

